# Use of /** so that the configurations hold for controller
# managers regardless of their namespace. Usefull in multi-robot setups.
/**/controller_manager:
  ros__parameters:
    update_rate: 500

    # ROS 2 control broadcasters
    right_arm_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    right_arm_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # right arm ROS 2 control broadcasters
    right_arm_state_broadcaster:
      type: lbr_ros2_control/LBRStateBroadcaster

    # ROS 2 control controllers
    right_arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # right_arm 2 control controllers
    right_arm_admittance_controller:
      type: lbr_ros2_control/AdmittanceController

    right_arm_joint_position_command_controller:
      type: lbr_ros2_control/LBRJointPositionCommandController

    right_arm_torque_command_controller:
      type: lbr_ros2_control/LBRTorqueCommandController

    right_arm_wrench_command_controller:
      type: lbr_ros2_control/LBRWrenchCommandController

    right_arm_twist_controller:
      type: lbr_ros2_control/TwistController

# ROS 2 control broadcasters
/**/right_arm_force_torque_broadcaster:
  ros__parameters:
    frame_id: right_arm_link_ee # namespace: https://github.com/ros2/rviz/issues/1103
    sensor_name: estimated_ft_sensor

# right arm ROS 2 control broadcasters
/**/right_arm_state_broadcaster:
  ros__parameters:
    robot_name: bh_robot

# ROS 2 control controllers
/**/right_arm_joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_arm_A1
      - right_arm_A2
      - right_arm_A3
      - right_arm_A4
      - right_arm_A5
      - right_arm_A6
      - right_arm_A7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

/**/right_arm_forward_position_controller:
  ros__parameters:
    joints:
      - right_arm_A1
      - right_arm_A2
      - right_arm_A3
      - right_arm_A4
      - right_arm_A5
      - right_arm_A6
      - right_arm_A7
    interface_name: position

# right_arm ROS 2 control controllers
/**/right_arm_joint_position_command_controller:
  ros__parameters:
    robot_name: bh_robot

/**/right_arm_torque_command_controller:
  ros__parameters:
    robot_name: bh_robot

/**/right_arm_wrench_command_controller:
  ros__parameters:
    robot_name: bh_robot

/**/right_arm_admittance_controller:
  ros__parameters:
    robot_name: bh_robot
    admittance:
      mass: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      damping: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      stiffness: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    inv_jac_ctrl:
      chain_root: right_arm_link_0
      chain_tip: right_arm_link_ee
      damping: 0.2 # damping factor for the pseudo-inverse of the Jacobian
      max_linear_velocity: 2.0 # maximum linear velocity
      max_angular_velocity: 2.0 # maximum linear acceleration
      joint_gains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # joint gains
      cartesian_gains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # cartesian gains

/**/right_arm_twist_controller:
  ros__parameters:
    robot_name: bh_robot
    inv_jac_ctrl:
      chain_root: right_arm_link_0
      chain_tip: right_arm_link_ee
      twist_in_tip_frame: true # if true, the twist command is expressed in the tip frame, otherwise in the root frame
      damping: 0.2 # damping factor for the pseudo-inverse of the Jacobian
      max_linear_velocity: 0.1 # maximum linear velocity
      max_angular_velocity: 0.1 # maximum linear acceleration
      joint_gains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # joint gains
      cartesian_gains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # cartesian gains
    timeout: 0.2 # stop controller if no command is received within this time [s]