urdf_path: "./urdf/dual_arm/dual_arm_w_grippers.urdf"
srdf_path: "./srdf/dual_arm/dual_arm_w_grippers.srdf"
joint_stiffness: 1000
joint_damping: 200
gripper_stiffness: 1000
gripper_damping: 200
move_group: ["left_arm_link_ee","right_arm_link_ee"]
ee_joints: ["left_arm_A7", "right_arm_A7"]
arm_joints_name: [["left_arm_A1", "left_arm_A2", "left_arm_A3", "left_arm_A4", "left_arm_A5", "left_arm_A6", "left_arm_A7"], ["right_arm_A1", "right_arm_A2", "right_arm_A3", "right_arm_A4", "right_arm_A5", "right_arm_A6", "right_arm_A7"]]
gripper_name:
  - base: "left_robotiq_hande_left_finger_joint"
    mimic: [["left_robotiq_hande_right_finger_joint", 1., 0.]]
  - base: "right_robotiq_hande_left_finger_joint"
    mimic: [["right_robotiq_hande_right_finger_joint", 1., 0.]]
gripper_bias: 0.155
gripper_scale: [-0.01, 0.045]
homestate: [[-2.7816389, -0.25712854, -0.54790103, 1.5019695, 0.9828859, -1.2982103, -0.8782399, 0.025, 0.025], [-0.7854, 0.39567, 0.39567,-1.22173, -0.47822, 1.272345, 0.0, 0.025, 0.025]]
# homestate: [[0,0,0,0,0,0,0.025,0.025],[0,0,0,0,0,0,0.025,0.025]]
delta_matrix: [[0,0,1],[0,-1,0],[1,0,0]]
global_trans_matrix: [[0,0,1],[1,0,0],[0,1,0]]
robot_pose: [[0, -0.7, 0.97, -1, 0, 0, 1]]
# planner: "mplib_screw"
planner: "curobo"
dual_arm: True
rotate_lim: [0, 1]
grasp_perfect_direction: ['right', 'left']
static_camera_list: 
- name: head_camera
  type: D435
  position:
  - -0.032
  - -0.45
  - 1.35
  forward:
  - 0
  - 0.6
  - -0.8
  left:
  - -1
  - 0
  - 0
- name: front_camera
  type: D435
  position:
  - 0
  - -0.45
  - 0.85
  forward:
  - 0
  - 1
  - -0.1
  left:
  - -1
  - 0
  - 0