urdf_path: "./urdf/dual_arm/dual_arm_w_grippers.urdf"
srdf_path: "./srdf/dual_arm/dual_arm_w_grippers.srdf"
joint_stiffness: 1000
joint_damping: 200
gripper_stiffness: 1000
gripper_damping: 200
move_group: ["left_arm","right_arm"]
ee_joints: ["left_arm_A7", "right_arm_A7"]
arm_joints_name: [["left_arm_A1", "left_arm_A2", "left_arm_A3", "left_arm_A4", "left_arm_A5", "left_arm_A6", "left_arm_A7"], ["right_arm_A1", "right_arm_A2", "right_arm_A3", "right_arm_A4", "right_arm_A5", "right_arm_A6", "right_arm_A7"]]
gripper_name:
  - base: "left_robotiq_hande_left_finger_joint"
    mimic: [["left_robotiq_hande_right_finger_joint", 1., 0.]]
  - base: "right_robotiq_hande_left_finger_joint"
    mimic: [["right_robotiq_hande_right_finger_joint", 1., 0.]]
gripper_bias: 0.12
gripper_scale: [-0.01, 0.045]
# homestate: [[0.057860993,1.1664766,1.0904326,0.6481283,0,1.156943,-0.1790052], [0.5341759,0.3204597,0.03399502,-1.7246392,1.4899178,1.0517951,0.05101651]]
homestate: [[0,0,0,0,0,0,0], [0,0,0,0,0,0,0]]
delta_matrix: [[1,0,0],[0,1,0],[0,0,1]]
global_trans_matrix: [[1,0,0],[0,-1,0],[0,0,-1]]
# robot_pose: [[0, -1.1, 0.75, 0.707, 0, 0, -0.707]] # Origional kuka base : robot does not move
robot_pose: [[0, -0.65, 0.0, 0.707, 0, 0, 0.707]]  # Base copied from aloha : at least robot moves, notice the main different is the rotation
# planner: "mplib_screw"
planner: "curobo"
dual_arm: True
rotate_lim: [0, 1]
grasp_perfect_direction: ['front_right', 'front_left']
static_camera_list: 
- name: head_camera
  type: D435
  position:
  - -0.032
  - -0.45
  - 1.35
  forward:
  - 0
  - 0.6
  - -0.8
  left:
  - -1
  - 0
  - 0
- name: front_camera
  type: D435
  position:
  - 0
  - -0.45
  - 0.85
  forward:
  - 0
  - 1
  - -0.1
  left:
  - -1
  - 0
  - 0