<?xml version="1.0"?>
<robot name="hardware" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- distance 0 0 0.152 center of mass 0.004 0.004 0.085 mass 2.4 main gripper macro -->

<!-- Macro for the inertia of a box -->
  <xacro:macro name="box_inertia" params="x y z mass">
    <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
      iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
      izz="${0.0833333 * mass * (x*x + y*y)}" />
  </xacro:macro>
<!-- Macro for, well, orange -->>
  <material name="Orange">
    <color rgba="1.0 0.423529411765 0.0392156862745 1.0"/>
  </material>

<xacro:macro name="table" params="parent *origin">
  
  <!-- table is height adjustable -->
  <xacro:property name="table_height" value="0.83" />
  <xacro:property name="table_width" value="0.8" />
  <xacro:property name="table_length" value="1.6" />
  <xacro:property name="table_frame_offset" value="0 0 ${table_height}" />

  <xacro:property name="plate_height" value="0.02" />
  <xacro:property name="plate_width" value="0.80" />
  <xacro:property name="plate_length" value="0.30" />

  <xacro:property name="PI" value="3.14159265359"/>
  
  <!-- retrieved from the manual -->
  <xacro:property name="iiwa_pin_distance" value="0.184" />

  <!--  Defines offset of the box representing the table -->
  <xacro:property name="box_offset" value="${table_length/2.} ${table_width/2.} ${table_height/2.}" />

  <!--  Define the origin of your 3D space
  Here we define a box lying at 0,0,0 with some dimensions, in reality our robot is place on top of a metal cart with those dimensions.
  This will include the cart in the scene and avoid the robot to hit it when using MoveIt!
  If you don't want to have that you can define a basic world link (see commented lines)
  -->
  <joint name="footprint_joint" type="fixed">
    <parent link="${parent}"/>
    <child link = "table_base_link"/>
    <xacro:insert_block name="origin" />
  </joint>

  <joint name="table_origin_joint" type="fixed">
    <parent link="table_base_link"/>
    <child link = "table_origin"/>
    <origin xyz="${table_frame_offset}" />
  </joint>

  <!-- x 185mm from the CAD plus 1mm shift in mounting position y centered half width of the table -->  
  <!-- <joint name="torso_origin_joint" type="fixed">
    <parent link="table_origin"/>
    <child link = "torso_origin"/>
    <origin xyz="0.186 ${table_width/2} 0" />
  </joint> -->
 

  <joint name="plate_1_inner_joint" type="fixed">
    <parent link="table_origin"/>
    <child link = "plate_1_inner"/>
    <origin xyz="${table_length-plate_length/2} ${0.102+iiwa_pin_distance/2} ${plate_height}" rpy="0 0 ${PI}" />
  </joint>

  <!-- commented out since they are typically not used
  <joint name="plate_1_outer_joint" type="fixed">
    <parent link="plate_1_inner"/>
    <child link = "plate_1_outer"/>
    <origin xyz="0 0.05 0" rpy="0 0 0" />
  </joint>
  -->

  <joint name="plate_2_inner_joint" type="fixed">
    <parent link="table_origin"/>
    <child link = "plate_2_inner"/>
    <origin xyz="${table_length-plate_length/2} ${plate_width-0.102-iiwa_pin_distance/2} ${plate_height}" rpy="0 0 ${PI}" />
  </joint>

  <!-- commented out since they are typically not used
  <joint name="plate_2_outer_joint" type="fixed">
    <parent link="plate_2_inner"/>
    <child link = "plate_2_outer"/>
    <origin xyz="0 -0.05 0" rpy="0 0 0" />
  </joint>
  -->

  <link name="table_origin">
  </link>

  <!-- <link name="torso_origin">
  </link> -->

  <!-- commented out since they are typically not used
  <link name="plate_1_outer">
  </link>
  -->

  <!-- this one is typically used -->
  <link name="plate_1_inner">
  </link>

  <!-- commented out since they are typically not used
  <link name="plate_2_outer">
  </link>
  -->

  <!-- this one is typically used -->
  <link name="plate_2_inner">
  </link>

  <link name="table_base_link">
    <inertial>
      <origin xyz="${box_offset}" rpy="0 0 0"/>
      <mass value="100.0"/>
      <xacro:box_inertia x="${table_length}" y="${table_width}" z="${table_height}" mass="100.0"/>
    </inertial>
    <visual>
      <origin xyz="${box_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${table_length} ${table_width} ${table_height}"/>
      </geometry>
      <material name="Orange"/>
    </visual>
    <collision>
      <origin xyz="${box_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${table_length} ${table_width} ${table_height}"/>
      </geometry>
    </collision>
  </link>

</xacro:macro>
</robot>
